package my.noveldoksuha.coreui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance

@Composable
fun ColorScheme.isLightTheme() = background.luminance() > 0.5

val light_colorScheme = ColorScheme(
    primary = Grey25,
    onPrimary = Grey900,
    primaryContainer = Indigo90,
    onPrimaryContainer = Indigo10,
    inversePrimary = Indigo80,
    secondary = Grey25,
    onSecondary = Grey900,
    secondaryContainer = ColorAccent,
    onSecondaryContainer = Indigo90,
    tertiary = Indigo40,
    onTertiary = Grey0,
    tertiaryContainer = Indigo90,
    onTertiaryContainer = Indigo10,
    background = Grey25,
    onBackground = Grey900,
    surface = Grey25,
    onSurface = Grey900,
    surfaceVariant = Indigo95,
    onSurfaceVariant = Color(0xFF49454F),
    surfaceTint = ColorAccent,
    inverseSurface = Grey800,
    inverseOnSurface = Grey50,
    error = Error300,
    onError = Grey0,
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF79747E),
    outlineVariant = Indigo90,
    scrim = Color(0x52000000),
    surfaceBright = Grey0,
    surfaceDim = Grey75,
    surfaceContainer = Indigo95,
    surfaceContainerHigh = Indigo90,
    surfaceContainerHighest = Indigo80,
    surfaceContainerLow = Grey50,
    surfaceContainerLowest = Grey0,
)

val dark_colorScheme = ColorScheme(
    primary = Grey900,
    onPrimary = Grey25,
    primaryContainer = Indigo30,
    onPrimaryContainer = Indigo90,
    inversePrimary = Indigo80,
    secondary = Grey900,
    onSecondary = Grey25,
    secondaryContainer = ColorAccent,
    onSecondaryContainer = Indigo90,
    tertiary = Indigo60,
    onTertiary = Indigo10,
    tertiaryContainer = Indigo20,
    onTertiaryContainer = Indigo90,
    background = Grey900,
    onBackground = Grey50,
    surface = Grey900,
    onSurface = Grey25,
    surfaceVariant = Color(0xFF2A2535),
    onSurfaceVariant = Indigo80,
    surfaceTint = Indigo60,
    inverseSurface = Grey100,
    inverseOnSurface = Grey900,
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF938F99),
    outlineVariant = Indigo20,
    scrim = Color(0x52000000),
    surfaceBright = Grey700,
    surfaceDim = Grey900,
    surfaceContainer = Color(0xFF1E1B27),
    surfaceContainerHigh = Color(0xFF2A2535),
    surfaceContainerHighest = Color(0xFF342F3F),
    surfaceContainerLow = Color(0xFF17141E),
    surfaceContainerLowest = Grey1000,
)

val black_colorScheme = ColorScheme(
    primary = Grey1000,
    onPrimary = Grey25,
    primaryContainer = Indigo20,
    onPrimaryContainer = Indigo90,
    inversePrimary = Indigo80,
    secondary = Grey1000,
    onSecondary = Grey25,
    secondaryContainer = ColorAccent,
    onSecondaryContainer = Indigo90,
    tertiary = Indigo50,
    onTertiary = Indigo10,
    tertiaryContainer = Indigo20,
    onTertiaryContainer = Indigo90,
    background = Grey1000,
    onBackground = Grey50,
    surface = Grey1000,
    onSurface = Grey25,
    surfaceVariant = Grey1000,
    onSurfaceVariant = Indigo70,
    surfaceTint = Indigo50,
    inverseSurface = Grey100,
    inverseOnSurface = Grey1000,
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF938F99),
    outlineVariant = Indigo20,
    scrim = Color(0x52000000),
    surfaceBright = Grey800,
    surfaceDim = Grey1000,
    surfaceContainer = Color(0xFF0D0B12),
    surfaceContainerHigh = Color(0xFF171420),
    surfaceContainerHighest = Color(0xFF201D2C),
    surfaceContainerLow = Color(0xFF080609),
    surfaceContainerLowest = Grey1000,
)
